name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
          - os: windows-latest
            cc: cl
            cxx: cl
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Linux Dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt update && sudo apt install cmake ninja-build

    - name: Build on Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build -S . -DCMAKE_INSTALL_PREFIX="$PWD/dist"
        cmake --build build --target all
        cmake --build build --target install

    - name: Build on Linux with vgui
      if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.cc, 'gcc')
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build-vgui -S . -DUSE_VGUI=ON -DCMAKE_INSTALL_PREFIX="$PWD/dist-vgui"
        cmake --build build-vgui --target all
        cmake --build build-vgui --target install

    - name: Set developer command prompt for Windows x86 (Visual Studio Ortamı)
      if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build on Windows x86
      if: startsWith(matrix.os, 'windows')
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build -S . -DCMAKE_INSTALL_PREFIX="dist"
        cmake --build build --target all
        cmake --build build --target install
    - name: Build on Windows x86 with vgui
      if: startsWith(matrix.os, 'windows')
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build-vgui -S . -DUSE_VGUI=ON -DCMAKE_INSTALL_PREFIX="dist-vgui"
        cmake --build build-vgui --target all
        cmake --build build-vgui --target install

    - name: Set developer command prompt for Windows x64 (Visual Studio Ortamı)
      if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build on Windows x64
      if: startsWith(matrix.os, 'windows')
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build64 -S . -DCMAKE_INSTALL_PREFIX="dist64" -D64BIT=ON
        cmake --build build64 --target all
        cmake --build build64 --target install

    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Extract gamedir
      shell: bash
      run: |
        if [[ -f build/CMakeCache.txt ]]; then
          echo "gamedir=$(grep build/CMakeCache.txt -Ee 'GAMEDIR:STRING=[a-z]+' | cut -d '=' -f 2 | head -n 1)" >> $GITHUB_OUTPUT
        elif [[ -f build64/CMakeCache.txt ]]; then
          echo "gamedir=$(grep build64/CMakeCache.txt -Ee 'GAMEDIR:STRING=[a-z]+' | cut -d '=' -f 2 | head -n 1)" >> $GITHUB_OUTPUT
        else
          echo "gamedir=custom_game" >> $GITHUB_OUTPUT
        fi
      id: extract_gamedir

    - name: Upload linux artifact
      if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-linux
        path: dist/${{ steps.extract_gamedir.outputs.gamedir }}

    - name: Upload linux artifact with vgui
      if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-linux-vgui
        path: dist-vgui/${{ steps.extract_gamedir.outputs.gamedir }}

    - name: Upload windows artifact (x86)
      if: startsWith(matrix.os, 'windows') && matrix.cc == 'cl'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows
        path: dist/${{ steps.extract_gamedir.outputs.gamedir }}

    - name: Upload windows x64 artifact
      if: startsWith(matrix.os, 'windows') && matrix.cc == 'cl'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows_x64
        path: dist64/${{ steps.extract_gamedir.outputs.gamedir }}

    - name: Upload windows artifact with vgui (x86)
      if: startsWith(matrix.os, 'windows') && matrix.cc == 'cl'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows-vgui
        path: dist-vgui/${{ steps.extract_gamedir.outputs.gamedir }}
